name: 🌞 Morning Premium Embed

on:
  schedule:
    - cron: '45 22 * * *'   # 6:00 sáng Việt Nam (Nếu free plan)
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: 📲 Send Embed
        run: |
          TZ="Asia/Ho_Chi_Minh"

          DAY_NUM=$(TZ=$TZ date +%u)

          case $DAY_NUM in
            1) DAY_NAME="Thứ Hai" ;;
            2) DAY_NAME="Thứ Ba" ;;
            3) DAY_NAME="Thứ Tư" ;;
            4) DAY_NAME="Thứ Năm" ;;
            5) DAY_NAME="Thứ Sáu" ;;
            6) DAY_NAME="Thứ Bảy" ;;
            7) DAY_NAME="Chủ Nhật" ;;
          esac

          if [ "$DAY_NUM" -eq 1 ]; then
            MESSAGE="💀 Thứ 2 rồi, dậy đi các anh em <@&1443084214156263424> !"
          elif [ "$DAY_NUM" -eq 7 ]; then
            MESSAGE="🌿 Chủ nhật chill nhưng nhớ chuẩn bị tuần mới <@&1443084214156263424> !"
          else
            MESSAGE="🚀 Chúc anh em một ngày đầy năng lượng <@&1443084214156263424> !"
          fi

          DATE_TEXT=$(TZ=$TZ date +"%d tháng %m năm %Y lúc %H:%M")
          ISO_TIME=$(TZ=$TZ date -u +"%Y-%m-%dT%H:%M:%SZ")

          curl -H "Content-Type: application/json" \
          -d "{
            \"username\": \"Kumo UI\",
            \"avatar_url\": \"https://i.ibb.co/B5N6tFhj/Le-Luoi.png\",
            \"embeds\": [{
              \"title\": \"🌞 Chào buổi sáng !\",
              \"description\": \"**$MESSAGE**\",
              \"color\": 16760576,
              \"image\": {
                \"url\": \"https://i.imgur.com/4M34hi2.png\"
              },
              \"footer\": {
                \"text\": \"🗓️ Hôm nay là $DAY_NAME, ngày $DATE_TEXT • Kumo UI • Được làm bởi M.Quân 😊\"
              },
              \"timestamp\": \"$ISO_TIME\"
            }]
          }" \
          ${{ secrets.WEBHOOK_URL }} 
