name: 🌞 Morning Premium Embed

on:
  schedule:
    - cron: '45 22 * * *'   # 6h sáng Việt Nam (Thứ 2 → Chủ Nhật)
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: 📲 Send Embed
        run: |
          DAY=$(date +%u)

          if [ "$DAY" -eq 2 ]; then
            MESSAGE="💀 Thứ 2 rồi ,dậy đi các anh em <@&1443084214156263424> !"
          elif [ "$DAY" -eq 1 ]; then
            MESSAGE="🌿 Chủ nhật chill nhưng nhớ chuẩn bị tuần mới <@&1443084214156263424> !"
          else
            MESSAGE="🚀 Chúc anh em một ngày đầy năng lượng <@&1443084214156263424> !"
          fi

          curl -H "Content-Type: application/json" \
          -d "{
            \"username\": \"Kumo UI\",
            \"avatar_url\": \"https://i.ibb.co/B5N6tFhj/Le-Luoi.png\",
            \"embeds\": [{
              \"title\": \"🌞 Chào buổi sáng !\",
              \"description\": \"**$MESSAGE**\",
              \"color\": 8900331,
              \"image\": {
                \"url\": \"https://i.imgur.com/4M34hi2.png\"
              },
              \"footer\": {
                \"text\": \"Kumo UI • Được làm bởi M.Quân\"
              },
              \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"
            }]
          }" \
          ${{ secrets.WEBHOOK_URL }} 
